name: "Propose New Technique"
description: Propose a new technique using a structured form
title: "Create new technique: [technique name]"
labels: ["content: new technique", "form input"]
body:
  - type: input
    id: technique-name
    attributes:
      label: Technique name
      description: The name for the technique (synonyms can be provided below).
      placeholder: Give this technique a name
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A short description of the technique (extended details can be provided below).
      render: text
      placeholder: Describe what this technique does
    validations:
      required: true
  - type: textarea
    id: synonyms
    attributes:
      label: Synonyms
      description: Other names that might be used for this technique (one per line, e.g. RAM dump, memory dump).
      render: text
  - type: textarea
    id: details
    attributes:
      label: Details
      description: A longer set of details can be provided to describe the technique.
      render: text
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Examples of cases where the technique can be used, or tools that offer the technique (one per line, e.g. FTK Imager, Magnet ACQUIRE).
      render: text
  - type: dropdown
    id: objective
    attributes:
      label: Objective
      description: Which objective does this technique fit under?
      options:
        - "Find potential digital evidence sources"
        - "Prioritize digital evidence sources"
        - "Preserve digital evidence"
        - "Acquire data"
        - "Gain access"
        - "Read data from digital evidence storage formats"
        - "Reduce data under consideration"
        - "Access partitions, volumes and file systems data"
        - "Extract artifacts stored by the operating system"
        - "Extract artifacts stored by applications"
        - "Extract artifacts, or content of specific types"
        - "Locate potentially relevant content"
        - "Review content for relevance"
        - "Detect anti-forensics and other anomalies"
        - "Establish identities"
        - "Create visualizations"
        - "Reconstruct events"
        - "Conduct research"
        - "Produce documentation"
        - Other (specify below)
    validations:
      required: true
  - type: input
    id: objective-other
    attributes:
      label: Propose new objective
      description: If your technique doesn't fit an existing objective, propose one here.
  - type: markdown
    attributes:
      value: |
        ## Weaknesses
        List any existing weakness IDs that apply, and/or propose new weaknesses below.
        Existing weaknesses can be browsed [here](https://github.com/SOLVE-IT-DF/solve-it/tree/main/data/weaknesses).
  - type: textarea
    id: existing-weaknesses
    attributes:
      label: Existing weakness IDs
      description: IDs of existing weaknesses that apply to this technique (one per line, e.g. W1004, W1014).
      render: text
  - type: textarea
    id: new-weaknesses
    attributes:
      label: Propose new weaknesses
      description: Describe new weaknesses for this technique (one per line, e.g. Imaging process may miss data in hidden areas).
      render: text
  - type: textarea
    id: case-input
    attributes:
      label: CASE input classes
      description: |
        Refer to [CASE Ontology A-Z](https://ontology.caseontology.org/documentation/entities-az.html)
        or the [SOLVE-IT Ontology A-Z](https://ontology.solveit-df.org/entities-az.html) for suitable classes (one per line).
      render: text
  - type: textarea
    id: case-output
    attributes:
      label: CASE output classes
      description: |
        Refer to [CASE Ontology A-Z](https://ontology.caseontology.org/documentation/entities-az.html)
        or the [SOLVE-IT Ontology A-Z](https://ontology.solveit-df.org/entities-az.html) for suitable classes (one per line).
        You can also propose a new CASE class via the [CASE Issue Tracker](https://github.com/casework/CASE/issues).
      render: text
  - type: textarea
    id: references
    attributes:
      label: References
      description: References to support any details provided above (one per line).
      render: text
  - type: textarea
    id: other-notes
    attributes:
      label: Any other notes
      description: Any additional information or context you'd like to provide.
