name: "Update Technique"
description: Propose changes to an existing technique
title: "Update technique: [Txxxx]"
labels: ["content: update technique", "form input"]
body:
  - type: markdown
    attributes:
      value: |
        ## Update an existing technique
        Use this form to propose changes to an existing technique.
        **Leave fields blank to keep current values.** Only fill in fields you want to change.
        Existing techniques can be browsed [here](https://github.com/SOLVE-IT-DF/solve-it/tree/main/data/techniques).
  - type: input
    id: technique-id
    attributes:
      label: Technique ID
      description: The ID of the technique to update (e.g. T1002).
      placeholder: T1002
    validations:
      required: true
  - type: input
    id: new-technique-name
    attributes:
      label: New technique name
      description: Leave blank to keep the current name.
  - type: textarea
    id: new-description
    attributes:
      label: New description
      description: Leave blank to keep the current description.
      render: text
  - type: textarea
    id: new-details
    attributes:
      label: New details
      description: Leave blank to keep the current details.
      render: text
  - type: textarea
    id: synonyms
    attributes:
      label: Synonyms
      description: |
        The complete new list of synonyms (one per line).
        Leave blank to keep the current list. If populated, this replaces the entire list.
      render: text
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        The complete new list of examples (one per line, e.g. FTK Imager, Magnet ACQUIRE).
        Leave blank to keep the current list. If populated, this replaces the entire list.
      render: text
  - type: textarea
    id: weakness-ids
    attributes:
      label: Weakness IDs
      description: |
        The complete new list of weakness IDs (one per line, e.g. W1004, W1014).
        Leave blank to keep the current list. If populated, this replaces the entire list.
        Existing weaknesses can be browsed [here](https://github.com/SOLVE-IT-DF/solve-it/tree/main/data/weaknesses).
      render: text
  - type: textarea
    id: case-output
    attributes:
      label: CASE output classes
      description: |
        The complete new list of CASE output classes (one per line).
        Leave blank to keep the current list. If populated, this replaces the entire list.
        Refer to [CASE Ontology A-Z](https://ontology.caseontology.org/documentation/entities-az.html)
        or the [SOLVE-IT Ontology A-Z](https://ontology.solveit-df.org/entities-az.html) for suitable classes.
      render: text
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        The complete new list of references (one per line).
        Leave blank to keep the current list. If populated, this replaces the entire list.
      render: text
  - type: textarea
    id: other-notes
    attributes:
      label: Any other notes
      description: Any additional information or context for the proposed changes.
